deployments:
  - name: s3-to-snowflake-dev
    entrypoint: ../flows/data_ingestion/s3_to_snowflake.py:s3_to_snowflake_flow
    tags:
      - dev
      - data-ingestion
    parameters:
      s3_bucket_block_name: dev-data-bucket
      s3_key: sample_data.csv
      table_name: sample_table
      schema: DEV_SCHEMA
      config_block_name: etl-config
      environment: dev
    schedule:
      cron: '0 */3 * * *' # Every 3 hours
    work_pool:
      name: default-agent-pool
      work_queue_name: default
    infrastructure:
      type: ecs-task
      task_definition_arn: ${PREFECT_ECS_TASK_DEFINITION_ARN}
      execution_role_arn: ${PREFECT_ECS_EXECUTION_ROLE_ARN}
      task_role_arn: ${PREFECT_ECS_TASK_ROLE_ARN}
      cluster: ${PREFECT_ECS_CLUSTER}
      launch_type: FARGATE
      env:
        ENVIRONMENT: dev
    description: 'DEV: Flow that loads data from S3 to Snowflake using AWS Secrets Manager'
