deployments:
  - name: s3-to-snowflake-dev
    entrypoint: ../flows/data_ingestion/s3_to_snowflake.py:s3_to_snowflake_flow
    tags:
      - dev
      - data-ingestion
    parameters:
      s3_bucket_block_name: dev-data-bucket
      s3_key: sample_data.csv
      snowflake_block_name: dev-snowflake
      table_name: sample_table
      schema: DEV_SCHEMA
      config_block_name: etl-config
    schedule:
      cron: '0 */3 * * *' # Every 3 hours
    work_pool:
      name: default-agent-pool
      work_queue_name: default
    infrastructure:
      type: process
      env:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
        SNOWFLAKE_USER: ${SNOWFLAKE_USER}
        SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
    description: 'DEV: Flow that loads data from S3 to Snowflake'
